name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 863518417758.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t somkheart:latest .
          docker tag somkheart:latest 863518417758.dkr.ecr.ap-southeast-1.amazonaws.com/somkheart:latest

      - name: Push to Lightsail Container
        run: |
          aws lightsail push-container-image --service-name your-lightsail-service --label latest --image 863518417758.dkr.ecr.ap-southeast-1.amazonaws.com/somkheart:latest

      - name: Deploy to Lightsail
        run: |
          aws lightsail create-container-service-deployment --service-name your-lightsail-service --containers file://container-definition.json
